name: BlackDuck-CI-SCACoverity # Name of the workflow
on:
  push:  # Trigger the workflow on push events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on push
  pull_request:  # Trigger the workflow on pull request events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on PR

jobs:
  build:  # Define a job named 'build'
    runs-on: [self-hosted]  # Specify the runner to execute the job
    #runs-on: [self-hosted, macOS, sh_mac_mdn]
    steps:  # List of steps to execute in this job
      - name: Checkout Source  # Step to check out the repository code
        uses: actions/checkout@v4 # Use the checkout action to clone the repo
      - name: Black Duck Coverity Scan  # Step for running a full CNC Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        #uses: blackduck-inc/black-duck-security-scan@SIGINT-3342
        
        with:
          bridgecli_download_url: https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.10.1rc3//bridge-cli-bundle-3.10.1rc3-macos_arm.zip
          #Scanning Reqiured Fileds ** CNC/Thin client
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          #coverity_version: "2025.9.0"
          #coverity_install_directory: "/Users/madhavanr/cove1"
          #coverity_project_name: "MDN_Coverity_CNC_Aug25"
          # coverity_stream_name:  "MDN_Coverity_CNC_Aug25"
        #  #Coverity Classic /Local 
          #coverity_url: ${{ secrets.COVERITY_CLASSIC_URL }}
          #coverity_user: ${{ secrets.COVERITY_CLASSIC_USER }}
          #coverity_passphrase: ${{ secrets.COVERITY_CLASSIC_PASSPHRASE }}
          #coverity_project_name: "MDN_Local_Coverity_Aug25_SCAN1"
          #coverity_stream_name:  "MDN_Local_Coverity_Aug25_SCAN1"
          #coverity_local: true
          coverity_waitforscan: false

         ### POLICY ENFORCEMENT: Uncomment to break build on policy
          coverity_policy_view: 'Outstanding Issues' 

        ### PULL REQUEST COMMENTS:
          coverity_prComment_enabled: true
          github_token: ${{ secrets.BD_GITHUB_TOKEN }}  # Black Duck API token from secrets
           
           ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
          include_diagnostics: true
         # Mark build status if policy violating issues are found
          mark_build_status: 'success'
