name: BlackDuck-CI-Polaris # Name of the workflow
on:
  push:  # Trigger the workflow on push events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on push
  pull_request:  # Trigger the workflow on pull request events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on PR
  workflow_dispatch:
jobs:
  build:  # Define a job named 'build'
    runs-on: [sh_mac_mdn_arm]  # Self Hosted Runner mac
    #runs-on: [self-hosted,linux, docker]  # Self Hosted Runner docker linux
    #runs-on: [ubuntu-latest]
    #runs-on: [windows-latest]
    steps:  # List of steps to execute in this job
      - name: Checkout Source  # Step to check out the repository code
        uses: actions/checkout@v4 # Use the checkout action to clone the repo
      - name: Polaris Full Scan  # Step for running a full CNC Scan
        uses: blackduck-inc/black-duck-security-scan@v2.4.0  # Use the Black Duck security scan action
        #uses: blackduck-inc/black-duck-security-scan@v2
        with:
           
           detect_args: '--detect.diagnostic=true'
           polaris_server_url: ${{secrets.POLARIS_SERVER_URL}}
           polaris_access_token: ${{secrets.POLARIS_ACCESS_TOKEN}}
           #bridgecli_download_url: https://repo.blackduck.com/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/3.9.0/bridge-cli-bundle-3.9.0-macos_arm.zip
          
          #polaris_server_url: ${{ secrets.POLARIS_PIM_SERVER_URL }}
          #polaris_access_token: ${{ secrets.POLARIS_PIM_ACCESS_TOKEN }}
          #polaris_server_url: ${{ secrets.POLARIS_CDEV_SERVER_URL }}
          #polaris_access_token: ${{ secrets.POLARIS_CDEV_ACCESS_TOKEN }}

          #bridgecli_download_url: https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.8.1rc1/bridge-cli-bundle-3.8.1rc1-macosx.zip
          #bridgecli_download_url: https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.9.0rc8/bridge-cli-bundle-3.9.0rc8-macosx.zip
          
          #bridgecli_download_url: https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/3.9.0rc8/bridge-cli-bundle-3.9.0rc8-linux64.zip
          #polaris_application_name: "Node_Goat_e2e"
          #polaris_project_name: "Node_Goat_e2e"
          # polaris_application_name: "Node_Goat_Repo_Test_Dir_Aug20"
          # polaris_project_name: "Node_Goat_Repo_Test_Dir_Aug20"
          #polaris_application_name: "Node_Goat_Repo_Test_Archive_Aug20"
          #polaris_project_name: "Node_Goat_Repo_Test_Archive_Aug20"

           polaris_assessment_types: "SCA,SAST"
           #polaris_assessment_types: "SAST"
           #polaris_assessment_types: "SCA"
          #polaris_assessment_types: "SAST"
          #coverity.version: "2025455.6.0"
          

          #Test Location - new resource
           polaris_test_sast_location: hybrid
           polaris_test_sca_location: hybrid
          
          ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
          #include_diagnostics: true

         ### Signature scan
          #polaris_test_sca_type: "SCA-SIGNATURE"
          #polaris_test_sca_type: "SCA-PACKAGE"

         #async mode
         # polaris_waitForScan: false  # Used to support the async mode

        ### Uncomment below configuration for source code upload 
          #project_directory: "/Users/madhavanr/GitHubTest_E2E/Repos/SastScaIssueSSS.zip"
          #polaris_assessment_mode: "SOURCE_UPLOAD"
          #polaris_assessment_mode: "CI"
          #project_directory: "/Users/madhavanr/GitHubTest_E2E/Repos/Node_Goat_e2e"
          #project_source_excludes: "artifacts,config,test,*.md,*.yml" # Accepts Multiple Values
          #project_source_archive: "/Users/madhavanr/GitHubTest_E2E/Repos/Node_Goat_e2e.zip"
          # project_source_preserveSymLinks: true
    
        ### SARIF report generation and upload to GitHub Adavanced Security Tab: Uncomment below to enable
           polaris_reports_sarif_create: true  
           polaris_reports_sarif_groupSCAIssues: true
        #   polaris_reports_sarif_issue_types: 'SCA,SAST'
        #   polaris_reports_sarif_file_path: '/Users/madhavanr/GitHubTest_E2E/sarif_Path/Polris_Sarif_Reports.json' # File path (including file name) where SARIF report is created.
        # polaris_reports_sarif_severities: "CRITICAL,HIGH"
        # polaris_upload_sarif_report: true 
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when polaris_upload_sarif_report is set as true

 ### Below configuration is used to enable feedback from Polaris security testing as pull request comment
           polaris_prComment_enabled: true
           github_token: ${{ secrets.BD_GITHUB_TOKEN }}
                ### Mark build status if policy violating issues are found
        # Rapid Scans
           #polaris_test_sast_Type: 'SAST_RAPID'   
          #polaris_test_sast_Type: 'SAST_FULL'      
           mark_build_status: 'success'

              
